net-tcp_bbr: v3: change `u64` to `unsigned long` for `bytes` in `bbr_tso_segs_generic`
This change addresses a build failure on 32-bit systems due to undefined division symbols:

arm:
ERROR: modpost: "__aeabi_uldivmod" [net/ipv4/tcp_bbr.ko] undefined!
ERROR: modpost: "__aeabi_ldivmod" [net/ipv4/tcp_bbr.ko] undefined!

x86, mips, ppc:
ERROR: modpost: "__udivdi3" [net/ipv4/tcp_bbr.ko] undefined!
ERROR: modpost: "__divdi3" [net/ipv4/tcp_bbr.ko] undefined!

Since `sk->sk_pacing_rate` is already an `unsigned long`, the `bytes` variable is
updated to `unsigned long` to resolve these division issues and ensure compatibility
across both 32-bit and 64-bit platforms.

Signed-off-by: Chen Minqiang <ptpt52@gmail.com>