packetdrill: run_all: make print python3+ compatible
When python3 is used, this syntax error about 'missing parentheses'
shows up:

  File \". packetdrill run_all.py\", line 114
    print 'stdout: '
                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print'stdout: '?

Rework the patch by adding parentheses to the print(...) function.

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>